SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = true;
SET client_min_messages = warning;
SET search_path = public, pg_catalog;
SET escape_string_warning = off;
SET default_tablespace = '';
SET default_with_oids = false;